[package]

name = "shiplift"
version = "0.0.1"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies.hyper]
path="/Users/dougtangren/code/rust/hyper"

[dependencies]
openssl = "0.5.0"
unix_socket = "0.2.1"
url = "0.2.26"