[package]

name = "shiplift"
version = "0.5.1"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A Rust interface for maneuvering Docker containers"
documentation = "https://docs.rs/shiplift"
homepage = "https://github.com/softprops/shiplift"
repository = "https://github.com/softprops/shiplift"
keywords = ["docker", "unix", "containers", "hyper", "ship"]
license = "MIT"
edition = "2018"
readme = "README.md"

[badges]
travis-ci = { repository = "softprops/shiplift" }
coveralls = { repository = "softprops/shipflit" }
maintenance = { status = "actively-developed" }

[dependencies]
base64 = "0.10"
bytes = "0.4"
chrono = { version = "0.4", optional = true, features = ["serde"] }
flate2 = "1.0"
futures = "0.3.1"
http = "0.1"
hyper = "0.13.0-alpha.4"
hyper-openssl = { version = "0.8.0-alpha.4", optional = true }
#hyperlocal = { version = "0.6", optional = true }
log = "0.4.6"
mime = "0.3.13"
openssl = { version = "0.10", optional = true, features = ["vendored"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
tokio = "0.2.0-alpha.5"
url = "1.7"
pin-project = "0.4.5"
async-codec = "0.4.0-alpha.2"
futures_codec = "0.3.1"

[dev-dependencies]
env_logger = "0.6"

[features]
#default = ["chrono", "unix-socket", "tls"]
default = ["chrono", "tls"]
#unix-socket = ["hyperlocal"]
tls = ["openssl", "hyper-openssl"]
