[package]

name = "shiplift"
version = "0.1.2"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A Rust interface for maneuvering Docker containers"
documentation = "https://softprops.github.io/shiplift"
homepage = "https://github.com/softprops/shiplift"
repository = "https://github.com/softprops/shiplift"
keywords = ["docker", "unix", "containers", "hyper", "ship"]
license = "MIT"

[dependencies]
mime = "0.0.11"
httparse = "0.1.3"
hyper = "0.5.2"
jed = "0.1.2"
openssl = "0.6.2"
unix_socket = "0.4.3"
url = "0.2.34"
rustc-serialize = "0.3.15"