[package]

name = "shiplift"
version = "0.1.2"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A Rust interface for maneuvering Docker containers"
documentation = "https://softprops.github.io/shiplift"
homepage = "https://github.com/softprops/shiplift"
repository = "https://github.com/softprops/shiplift"
keywords = ["docker", "unix", "containers", "hyper", "ship"]
license = "MIT"

[dependencies]
mime = "0.1"
httparse = "0.1"
jed = "0.1"
openssl = "0.6"
unix_socket = "0.4"
url = "0.2"
rustc-serialize = "0.3"

[dependencies.hyper]
version = "0.6"
features = ["openssl", "timeouts"]