[package]

name = "shiplift"
version = "0.0.1"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A modern multi-transport syslog appender."
documentation = "https://github.com/softprops/shiplift"
homepage = "https://github.com/softprops/shiplift"
repository = "https://github.com/softprops/shiplift"
keywords = ["docker", "unix", "containers", "hyper"]
license = "MIT"

[dependencies]
mime = "0.0.11"
httparse = "0.1.1"
hyper = "0.4.0"
jed = "0.1.1"
openssl = "0.6.2"
unix_socket = "0.3.2"
url = "0.2.31"
rustc-serialize = "0.3.14"